export const servicesData = [
  {
    id: 1,
    title: "Korporativ Hüquq",
    desc: "Korporativ hüquq korporasiyaların və digər hüquqi şəxslərin yaradılması, idarə edilməsi və fəaliyyətini tənzimləyən hüquq sahəsidir. Bu hüquq sahəsi korporasiyaların (şirkətlərin) hüquq və vəzifələrini, menecerlərin və direktorların məsuliyyətini, səhmdarların hüquqlarını və digər müvafiq məsələləri əhatə edir. Korporativ hüquqda həmçinin, şirkətlərin korporativ idarəetmə standartlarını və ən yaxşı təcrübələri təmin etmək üçün normativ sənədlər və kodekslərdən də istifadə edilir. ",
    services: [
      "Yerli və xarici hüquqi şəxslərin təsis olunması, sənədlərin hazırlanması və qeydiyyatı;",
      "Hüquqi şəxslərin təsis sənədlərində dəyişikliklərin, əlavələrin, dövlət qeydiyyatına alınması;",
      "Hüquqi şəxslərin birləşmə, qoşulma, bölünmə, ayrılma şəklində yenidən təşkili;",
      "Filial, şöbə, nümayəndəliklərin təsis edilməsi;",
      "Hüquqi şəxslərin qeydiyyatının ləğv edilməsi və ya dayandırılması;",
      "Hüquqi şəxslərin fəaliyyətinin hüquqi ekspertizası (due diligence);",
      "Müxtəlif istiqamətlər üzrə müqavilələrin hazırlanması;",
      "Hüquqi şəxslərin nizamnaməsinin, daxili qaydalarının, əsasnamələrinin, starteji sənədlərinin hazırlanması;",
      "Korporativ mübahisələrin həlli.",
    ],
  },
  {
    id: 2,
    title: "Əmək münasibətləri",
    desc: "Əmək hüququ, işçi və işəgötürən arasında olan hüquq və vəzifələri tənzimləyən hüquq sahəsidir. Bu sahə işçilərin işə qəbul olunması, iş şərtləri, əmək haqqı, iş vaxtı, məzuniyyət, iş təhlükəsizliyi və sağlamlığı, işə xitam verilməsi və kollektiv müqavilələr kimi mövzuları da əhatə edir. Əmək hüququ işçilərin hüquqlarını qorumaq, işəgötürənlə işçi arasındaki münasibətlərdə balans yaratmaq və əmək münasibətlərini ədalətli və şəffaf qaydalarla tənzimləmək məqsədi daşıyır. Əmək hüququ işçilər və işəgötürənlər arasında ədalətli iş şəraitini təmin etmək məqsədilə milli qanunvericiliklə yanaşı, beynəlxalq müqavilələr və təşkilatlar tərəfindən də tənzimlənir. Bu hüquq sahəsi, işçilərin sosial və iqtisadi hüquqlarının müdafiə edilməsinə, əmək münasibətlərinin daha şəffaf və ədalətli qaydada tənzimlənməsinə xidmət edir.",
    services: [
      "İşçilərin işə qəbul və işdən azad edilməsi ilə bağlı hüquqi rəyin verilməsi;",
      "Əmək, məxfilik, maddi məsuliyyət və digər müqavilələrin hazırlanması və ya ekspertizası;",
      "	Məzuniyyət, ezamiyyət prosesinin həyata keçirilməsilə bağlı hüquqi rəylərin verilməsi və prosedurlar aparılması;",
      "Mövcud əmək münasibətlərinin əmək qanunvericiliyinə uyğunluğunu yoxlamaq və ona nəzarət etmək;",
      "Əmək münasibətləri ilə əlaqədar tərtib olunmuş müəssisədaxili sənədlərin qanunauyğunluğunun yoxlanılması;",
      "İşçilərin və işəgötürənlərin mənafelərinin qorunması üçün məhkəməyədək və məhkəmə proseslərində hüquqi dəstək göstərilməsi.",
    ],
  },
  {
    id: 3,
    title: "Müqavilə Hüququ",
    desc: "Müqavilə hüququ, şəxslər və ya təşkilatlar arasında bağlanan müqavilələrin yaranmasını, icrasını və pozulmasını tənzimləyən hüquq sahəsidir. Bu sahə, müqavilələrin hüquqi tənzimlənməsi üçün lazım olan şərtləri, tərəflərin hüquq və vəzifələri, həmçinin məsuliyyətləri ilə bağlı nəticələri müəyyən edir. Müqavilə hüququ həm şifahi, həm də yazılı müqavilələri əhatə edir, lakin bəzi hallarda, o cümlədən, xüsusilə əhəmiyyətli və mürəkkəb müqavilələrdə, yazılı formada olması tələb olunur. Bu hüquq sahəsi, həmçinin, müqavilələrin etibarlılığı, şərtlərinin izahı və dəyişdirilməsi, və müqavilə bağlamaq qabiliyyətinə malik olan şəxslərin hüquqi vəziyyəti kimi məsələləri də əhatə edir.",
    services: [
      "Alqı-satqı, podrat, tapşırıq, bağışlama, kirayə, icarə, distribütorluq, əməkdaşlıq və digər növ müqavilələrin hazırlanması",
      "Xarici elementli müqavilələrin, həmçinin ticarət müqavilələrinin tərtib olunması və ekspertizası;",
      "Təqdim olunmuş bütün növ müqavilələrin hüquqi ekspertizasını aparmaq;",
      "Daşınmaz əmlakın dövlət qeydiyyatına alınması prosedurlarının icrası;",
      "İpoteka müqavilələrinin tərtibi, onların hüquqi təhlili;",
      "Müqavilərə əlavə və dəyişikliklərin edilməsi, xitamını həyata keçirmək;",
      "Müqavilələr üzrə yaranmış mübahisələrin həlli üçün məhkəməyədək (arbitraj) və məhkəmə proseslərində hüquqi dəstək göstərilməsi.",
    ],
  },
  {
    id: 4,
    title: "Sığorta Hüququ",
    desc: "Sığorta hüququ, sığorta müqavilələrinin bağlanması, icrası və tənzimlənməsi ilə əlaqəli hüquqi qaydaları və prinsipləri əhatə edən hüquq sahəsidir. Bu sahə, sığorta şirkətləri və sığortalılar (sığorta alanlar) arasında olan hüquq və vəzifələri, sığorta hadisələri zamanı ödəniş prosedurlarını və sığorta sahəsində yaranan mübahisələrin həllini tənzimləyir. Sığorta hüququ, sığorta sektorunun təhlükəsiz və ədalətli fəaliyyətini təmin etmək, sığortaçılar və sığortalılar arasında balans yaratmaq və sığorta ödənişlərinin düzgün və vaxtında həyata keçirilməsini təmin etmək üçün mühüm rol oynayır. Bu hüquq sahəsi, həm milli qanunvericilik, həm də beynəlxalq müqavilələr və standartlar vasitəsilə tənzimlənir.",
    services: [
      "Sığorta fəaliyyətilə bağlı lisenziyaların alınmasına hüquqi dəstək",
      "Həyat, daşınmaz əmlak, nəqliyyat, səyahət, tibbi sığorta müqavilələrinin hazırlanması, ləğvi və onun hüquqi ekspertizası;",
      "Sığorta müqavilələrindən yaranan mübahisələrin təhlili və onların hüquqi həlli;",
      "Həyat, əmlak, mülki məsuliyyət və digər sığorta mübahisələrinə dair konsultasiya.",
    ],
  },
  {
    id: 5,
    title: "İnzibati Hüquq",
    desc: "İnzibati hüquq, dövlət idarəçiliyi və dövlət orqanlarının fəaliyyətini tənzimləyən hüquq sahəsidir. Bu sahə dövlət orqanlarının və idarələrinin səlahiyyətlərini, vəzifələrini, fəaliyyət qaydalarını və vətəndaşlarla münasibətlərini tənzimləyir. İnzibati hüququn məqsədi, dövlət idarəçiliyinin hüquqi əsaslarını müəyyən etmək, idarəetmənin qanunauyğunluğunu və şəffaflığını təmin etmək və vətəndaşların dövlət orqanları ilə qarşılıqlı əlaqələrində hüquqlarını qorumaqdır. İnzibati hüquq, dövlət idarəetməsinin qanun çərçivəsində həyata keçirilməsini təmin etmək və vətəndaşların hüquqlarını qorumaq məqsədi daşıyır. Bu sahə, hüquqi dövlət prinsipinin və demokratik idarəetmənin əsasını təşkil edir.",
    services: [
      "Şəxslər üçün hüquqi rəylərin, arayışların, inzibati orqanlara ünvanlanacaq istənilən növ hüquqi sənədlərin hazırlanması;",
      "İnzibati orqanların qərarlarından şikayətlərin verilməsi.",
    ],
  },
  {
    id: 6,
    title: "Əqli Mülkiyyət Hüququ",
    desc: "Əqli mülkiyyət hüququ (ƏMH) şəxslərin intellektual yaradıcılıq fəaliyyəti nəticəsində ortaya çıxan əsərlərə və ixtiralara dair hüquqlarının mühafizə altına alınmasını təmin edən hüquq sahəsidir. Bu sahə, müəllif hüquqları, patentlər, əmtəə nişanları, coğrafi göstəricilər və sənaye dizaynları kimi müxtəlif əqli mülkiyyət növlərini əhatə edir. ƏMH, yaradıcılıq fəaliyyətini təşviq etmək və həmin fəaliyyət nəticəsində yaranan məhsulların qanunsuz istifadəsinə qarşı mühafizəsini təmin etmək məqsədi daşıyır. Əqli mülkiyyət hüququnun tənzimlənməsi milli qanunvericiliklə yanaşı, beynəlxalq müqavilələr və təşkilatlar tərəfindən də həyata keçirilir. Əqli mülkiyyət hüququnun məqsədi yaradıcılıq və innovasiyanı təşviq etmək, yaradıcı şəxslərə və şirkətlərə öz işlərindən iqtisadi fayda götürmək imkanı vermək, və bu hüquqların pozulmasına qarşı müdafiəni təmin etməkdir. Bu sahə, həm də iqtisadi inkişafa, mədəniyyətin və elmin inkişafına töhfə verir.",
    services: [
      "Əqli mülkiyyət obyektlərinin (ixtira, faydalı model, sənaye nümunəsi, əmtəə nişanları və coğrafi göstəricilərin) qeydiyyata alınması üçün iddia sənədlərinin tərtib edilməsi, bununla bağlı müvafiq patent müvəkkili ilə danışıqlar və əməkdaşlıq aparılması, sənədlərin müvafiq orqanlara təqdim edlməsi;",
      "Müvafiq orqanların ixtira, faydalı model və sənayə nümunələrinə patent verilməsindən və əmtəə nişanı və coğrafi göstəricilərin qeydə alınmasından imtina barədə qərarlarından etirazların hazırlanıb təqdim olunması;",
      "Əqli mülkiyyətlə bağlı digər xidmətlərin göstərilməsi.",
    ],
    note: "* Patent və əmtəə nişanlarının qeydiyyatı tərəfimizdən əməkdaşlıq etdiyimiz  patent müvəkkilləri vasitəsilə həyata keçirilir. ",
  },
  {
    id: 7,
    title: "Ailə Hüququ",
    desc: "Ailə hüququ, ailə münasibətlərini və ailə üzvlərinin hüquq və vəzifələrini tənzimləyən hüquq sahəsidir. Bu hüquq sahəsi nikah, boşanma, valideyn-övlad münasibətləri, aliment, ər-arvadın əmlakının qanuni rejmi və ailə üzvlərinin hüquqi statusu ilə bağlı məsələləri əhatə edir. Ailə hüququ, ailə üzvlərinin hüquqlarını qorumaq və ailə münasibətlərini hüquqi çərçivədə tənzimləmək məqsədi daşıyır. Ailə hüququ, ailə üzvləri arasında münasibətlərin ədalətliliyini təmin etmək üçün mühüm rol oynayır. Bu sahə, ailə üzvlərinin hüquqlarını qorumaq və ailə daxilində yaranan mübahisələrin qanun çərçivəsində həllini təmin etmək məqsədi daşıyır. Ailə hüququ milli qanunvericiliklə yanaşı, bir sıra beynəlxalq müqavilə və konvensiyalarla da tənzimlənir.",
    services: [
      "Nikah müqavilələrin hazırlanması;",
      "Nikaha daxil olma, boşanma;",
      "Əmlak bölgüsü;",
      "Aliment;",
      "Övladlığa götürmə;",
      "Uşaqla münasibət;",
      "Ailə münasibətləri ilə əlaqədar hüquqi konsultasiya.",
    ],
  },
  {
    id: 8,
    title: "Miqrasiya hüququ",
    desc: "Miqrasiya hüququ, şəxslərin bir ölkədən başqa bir ölkəyə köçmələri və həmin ölkədə yaşamaları ilə bağlı hüquqları və prosedurları tənzimləyən hüquq sahəsidir. Miqrasiya hüququ, mühacirlərin hüquqlarını qorumaq, ölkələrarası miqrasiya proseslərini tənzimləmək və miqrasiya ilə bağlı yaranan problemlərin həllini təmin etmək məqsədi daşıyır. Miqrasiya hüququ, insanların sərbəst hərəkət etmək hüquqlarını qorumaq və bu prosesin qanuni və ədalətli qaydalar çərçivəsində həyata keçirilməsini təmin etmək üçün mühüm rol oynayır. Bu hüquq sahəsi, miqrantların hüquqlarını müdafiə etməklə yanaşı, ölkələrin miqrasiya siyasətlərini də tənzimləyir və miqrasiya ilə bağlı yaranan sosial, iqtisadi və mədəni problemlərin həllinə töhfə verir.",
    services: [
      "Olduğu yer üzrə qeydiyyata alınma və müvəqqəti və daimi yaşamaq üçün icazələrin alınması;",
      "Əcnəbi şəxslərin işçi kimi cəlb edilməsi və istifadəsi üçün icazə sənədlərin alınması;",
      "Şirkətin miqrasiya hüququ sahəsində fəaliyyətinə hüquqi dəstək;",
      "Azərbaycan ərazisində xarici vətəndaşların qeydiyyatı prosedurunun həyata keçirilməsi;",
      "Əcnəbilərin işə götürülmə prosesində qanunla nəzərdə tutulmuş bütün lazımi sənədlərin çatdırılmasını təmin etmək;",
      "Miqrasiya orqanlarına təkrar müraciətlərin (müvəqqəti yaşamaq icazəsinin, visa müddətlərinin uzadılması və s.) edilməsi.",
    ],
  },
];
